uploads = []
outputs = []

[[generated]]
id = "_cCcJ_hT9ESMgNKPRT5sY"
uri = "file://artifacts/marangoz/src/assets/hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "isaDjWXtLMMN-gddwAlY-"
uri = "file://artifacts/marangoz/src/assets/door-classic.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tjBvGCg1u1tZLtLRCfRYy"
uri = "file://artifacts/marangoz/src/assets/door-modern.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LbKU0VpojRj9EP7AEoD-u"
uri = "file://artifacts/marangoz/src/assets/wardrobe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DiRFyzMK6iJ1BDnlhBKrx"
uri = "file://artifacts/marangoz/src/assets/grain.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LnP8Qf_IMyAMjSylIWOgg"
uri = "file://artifacts/marangoz/src/assets/craftsman.png"
type = "image"
title = "generated_image"
